export const countries={
    
       "Romania": [
             "Bucharest", 
              "Ia\u015fi", 
              "Cluj-Napoca", 
              "Timi\u015foara",
              "Gala\u0163i",
              "Bra\u015fov",
              "Craiova",
              "Constan\u0163a",
              "Ploie\u015fti",
              "Oradea",
              "Br\u0103ila",
              "Bac\u0103u",
              "Pite\u015fti",
              "Arad",
              "Sibiu",
              "T\u00e2rgu-Mure\u015f",
              "Baia Mare",
              "Buz\u0103u",
              "Boto\u015fani",
              "Satu Mare",
              "R\u00e2mnicu V\u00e2lcea",
              "Drobeta-Turnu Severin",
              "Scheia",
              "Foc\u015fani",
              "Piatra Neam\u0163",
              "T\u00e2rgu Jiu",
              "Tulcea",
              "T\u00e2rgovi\u015fte",
              "Re\u015fi\u0163a",
              "Bistri\u0163a",
              "Salcia",
              "C\u0103l\u0103ra\u015fi",
              "Vaslui",
              "Giurgiu",
              "Deva",
              "Alba Iulia",
              "Zal\u0103u",
              "Sf\u00e2ntu-Gheorghe",
              "Slobozia",
              "Alexandria",
              "Hunedoara",
              "Miercurea-Ciuc",
              "Slatina",
              "Suceava"      
       ]
    
    
}