//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proiectfinalpssc.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class CUSTOMER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CUSTOMER()
        {
            this.TRANSACTIONS = new HashSet<TRANSACTION>();
            FIRSTNAME = "0";
        }
        [Required(ErrorMessage ="This field is required")]
        public string IBAN { get; set; }
        [Required(ErrorMessage = "This field is required")]
        public string USERNAME { get; set; }
        [DataType(DataType.Password)]
        public string PASSWORD { get; set; }
        [Required(ErrorMessage = "This field is required")]
        public string FIRSTNAME { get; set; } // this functions get and sets the balance of the account
        [Required(ErrorMessage = "This field is required")]
        public string LASTNAME { get; set; }


    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRANSACTION> TRANSACTIONS { get; set; }
    }
}
