//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Runtime.Serialization;

namespace Proiectfinalpssc.Models
{
    [Serializable]
    internal class NotValidTransferSumException : Exception
    {
        public NotValidTransferSumException()
        {
        }

        public NotValidTransferSumException(string message) : base(message)
        {
        }

        public NotValidTransferSumException(string message, Exception innerException) : base(message, innerException)
        {
        }

        protected NotValidTransferSumException(SerializationInfo info, StreamingContext context) : base(info, context)
        {
        }
    }
}