//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistem_gestiune_vanzari.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbSistem_gestiune_vanzariEntities : DbContext
    {
        public dbSistem_gestiune_vanzariEntities()
            : base("name=dbSistem_gestiune_vanzariEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Tabel_Categorie> Tabel_Categorie { get; set; }
        public virtual DbSet<Tabel_Client> Tabel_Client { get; set; }
        public virtual DbSet<Tabel_Producator> Tabel_Producator { get; set; }
        public virtual DbSet<Tabel_Produs> Tabel_Produs { get; set; }
        public virtual DbSet<Table_Login> Table_Login { get; set; }
    }
}
