//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistem_gestiune_vanzari.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tabel_Categorie
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tabel_Categorie()
        {
            this.Tabel_Produs = new HashSet<Tabel_Produs>();
        }
    
        public int identitate_categorie { get; set; }
        public string nume_categorie { get; set; }
        public Nullable<bool> categorie_activa { get; set; }
        public Nullable<bool> categorie_stearsa { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tabel_Produs> Tabel_Produs { get; set; }
    }
}
