//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistem_gestiune_vanzari.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tabel_Client
    {
        public int identitate_client { get; set; }
        public string nume_client { get; set; }
        public string prenume_client { get; set; }
        public string adresa_client { get; set; }
        public string email_client { get; set; }
        public string parola_client { get; set; }
    }
}
