//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistem_gestiune_vanzari.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tabel_Produs
    {
        public string identitate_produs { get; set; }
        public Nullable<int> identitate_categorie { get; set; }
        public string nume_produs { get; set; }
        public string descriere { get; set; }
        public Nullable<int> cantitate { get; set; }
        public Nullable<decimal> cost { get; set; }
        public Nullable<decimal> pret { get; set; }
        public Nullable<int> identitate_producator { get; set; }
        public string imagine { get; set; }
        public Nullable<bool> produs_activ { get; set; }
        public Nullable<bool> produs_dezactivat { get; set; }
    
        public virtual Tabel_Categorie Tabel_Categorie { get; set; }
        public virtual Tabel_Producator Tabel_Producator { get; set; }
    }
}
