-- MySQL Script generated by MySQL Workbench
-- Tue Nov 26 16:29:15 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Projects`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Projects` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Projects` (
  `project_id` INT NOT NULL,
  `project_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`project_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Functionality`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Functionality` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Functionality` (
  `functionality_id` INT NOT NULL,
  `functionality_name` VARCHAR(45) NULL,
  PRIMARY KEY (`functionality_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Testers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Testers` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Testers` (
  `tester_id` INT NOT NULL,
  `tester_name` VARCHAR(45) NULL,
  `project_role` VARCHAR(45) NULL,
  `Projects_project_id` INT NOT NULL,
  PRIMARY KEY (`tester_id`),
  INDEX `fk_Testers_Projects1_idx` (`Projects_project_id` ASC) VISIBLE,
  CONSTRAINT `fk_Testers_Projects1`
    FOREIGN KEY (`Projects_project_id`)
    REFERENCES `mydb`.`Projects` (`project_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Tests`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Tests` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Tests` (
  `test_id` INT NOT NULL,
  `test_title` VARCHAR(45) NOT NULL,
  `test_description` VARCHAR(1024) NULL,
  `date_created` DATE NULL,
  `functionality` VARCHAR(45) NULL,
  `tester_id` INT NULL,
  `revision_history` VARCHAR(24) NULL,
  `Projects_project_id` INT NOT NULL,
  `Functionality_functionality_id` INT NOT NULL,
  `Testers_tester_id` INT NOT NULL,
  PRIMARY KEY (`test_id`),
  INDEX `fk_Tests_Projects_idx` (`Projects_project_id` ASC) VISIBLE,
  INDEX `fk_Tests_Functionality1_idx` (`Functionality_functionality_id` ASC) VISIBLE,
  INDEX `fk_Tests_Testers1_idx` (`Testers_tester_id` ASC) VISIBLE,
  CONSTRAINT `fk_Tests_Projects`
    FOREIGN KEY (`Projects_project_id`)
    REFERENCES `mydb`.`Projects` (`project_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Tests_Functionality1`
    FOREIGN KEY (`Functionality_functionality_id`)
    REFERENCES `mydb`.`Functionality` (`functionality_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Tests_Testers1`
    FOREIGN KEY (`Testers_tester_id`)
    REFERENCES `mydb`.`Testers` (`tester_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
