//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PsscApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UtilizatoriTable
    {
        public int CustomerID { get; set; }
        public string Nume_utilizator { get; set; }
        public string Parola { get; set; }
        public string email { get; set; }
    }
}
