# Generated by Django 2.2.6 on 2020-01-05 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0002_rfidkeysmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rfidkeysmodel',
            name='key',
            field=models.CharField(blank=True, max_length=13),
        ),
    ]
