// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WeTestBackend.Repositories;

namespace WeTestBackend.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    [Migration("20191210200736_WeTestBackend.Repositories.RepositoryContext")]
    partial class WeTestBackendRepositoriesRepositoryContext
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WeTestBackend.Models.Test", b =>
                {
                    b.Property<string>("TestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AuthorTesterId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Functionality")
                        .HasColumnType("int");

                    b.Property<string>("TestTitle")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TestId");

                    b.HasIndex("AuthorTesterId");

                    b.ToTable("Tests");
                });

            modelBuilder.Entity("WeTestBackend.Models.Tester", b =>
                {
                    b.Property<string>("TesterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TesterName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TesterId");

                    b.ToTable("Testers");
                });

            modelBuilder.Entity("WeTestBackend.Models.Test", b =>
                {
                    b.HasOne("WeTestBackend.Models.Tester", "Author")
                        .WithMany("TestsCollection")
                        .HasForeignKey("AuthorTesterId");
                });
#pragma warning restore 612, 618
        }
    }
}
